"""Pixiv 下载流程使用的解析、索引与任务规划组件。"""

from .batch import (
    BatchResult,
    execute_batch_tasks,
    find_missing_records,
    record_rows_to_tasks,
    unresolved_chapter_numbers,
)
from .config import (
    DEFAULT_CHAPTER_DELAY,
    DEFAULT_HEADERS,
    DEFAULT_MAX_RETRIES,
    DEFAULT_REQUEST_TIMEOUT,
    DEFAULT_RETRY_DELAY,
    build_request_headers,
    load_cookie_file,
)
from .endpoints import (
    illustration_detail_url,
    novel_detail_url,
    series_content_url,
    series_overview_url,
)
from .indexes import (
    load_record_rows,
    regenerate_summary,
    save_chapter_record,
    save_metadata_record,
    sum_word_count_from_metadata,
    update_series_catalog,
)
from .http import decode_json_response, request_with_retry, write_stream_response
from .novel import (
    cover_extension,
    localize_embedded_images,
    localize_referenced_images,
    parse_novel_payload,
    save_series_cover,
    select_cover_url,
)
from .novel_flow import DownloadedNovel, NovelApiError, fetch_and_save_novel
from .paths import (
    build_chapters_dir,
    build_cover_file,
    build_images_dir,
    build_metadata_file,
    build_novel_output_dir,
    build_record_file,
    build_series_catalog_file,
    build_series_info_file,
    build_series_output_dir,
    build_summary_file,
    chapter_file_exists,
    ensure_directory,
    find_existing_cover,
    normalize_chapter_number,
)
from .parsing import (
    clean_filename,
    clean_html,
    extract_tag_names,
    parse_chapter_selection,
    parse_pixiv_novel_id,
    parse_pixiv_series_id,
)
from .series import (
    build_series_tasks,
    collect_series_page,
    extract_series_contents,
    initial_series_metadata,
    merge_series_page_metadata,
    next_series_cursor,
    normalize_series_update_time,
    parse_series_overview,
    render_series_info,
)
from .series_flow import (
    SeriesApiError,
    SeriesCatalog,
    execute_series_tasks,
    fetch_series_catalog,
    fetch_series_overview,
)

__all__ = [
    "BatchResult",
    "build_request_headers",
    "build_series_tasks",
    "build_chapters_dir",
    "build_cover_file",
    "build_images_dir",
    "build_metadata_file",
    "build_novel_output_dir",
    "build_record_file",
    "build_series_catalog_file",
    "build_series_info_file",
    "build_series_output_dir",
    "build_summary_file",
    "chapter_file_exists",
    "clean_filename",
    "clean_html",
    "cover_extension",
    "collect_series_page",
    "decode_json_response",
    "DEFAULT_CHAPTER_DELAY",
    "DEFAULT_HEADERS",
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_REQUEST_TIMEOUT",
    "DEFAULT_RETRY_DELAY",
    "extract_series_contents",
    "extract_tag_names",
    "ensure_directory",
    "execute_batch_tasks",
    "execute_series_tasks",
    "find_existing_cover",
    "find_missing_records",
    "fetch_and_save_novel",
    "fetch_series_catalog",
    "fetch_series_overview",
    "illustration_detail_url",
    "initial_series_metadata",
    "load_record_rows",
    "load_cookie_file",
    "localize_embedded_images",
    "localize_referenced_images",
    "merge_series_page_metadata",
    "next_series_cursor",
    "normalize_chapter_number",
    "normalize_series_update_time",
    "novel_detail_url",
    "NovelApiError",
    "parse_chapter_selection",
    "parse_pixiv_novel_id",
    "parse_pixiv_series_id",
    "parse_novel_payload",
    "parse_series_overview",
    "regenerate_summary",
    "record_rows_to_tasks",
    "request_with_retry",
    "render_series_info",
    "save_chapter_record",
    "save_metadata_record",
    "save_series_cover",
    "sum_word_count_from_metadata",
    "select_cover_url",
    "SeriesApiError",
    "SeriesCatalog",
    "series_content_url",
    "series_overview_url",
    "update_series_catalog",
    "unresolved_chapter_numbers",
    "write_stream_response",
    "DownloadedNovel",
]
